name: Makinon
options:
  minimumXcodeGenVersion: 2.30.0

targets:
  Makinon:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - App
    settings:
      base:
        INFOPLIST_FILE: App/Info.plist
        CODE_SIGN_ENTITLEMENTS: App/Makinon.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.makkuenon.makinon
        DEVELOPMENT_TEAM: KRNONEKEYS
        SWIFT_VERSION: 5.0
    scheme:
      testTargets: []
